# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: policy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "policy.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cpolicy.proto\x12\x0crobot_teleop"\x84\x01\n\x14PolicyStepAnnotation\x12\x1a\n\x12inference_begin_ns\x18\x01 \x01(\x03\x12\x18\n\x10inference_end_ns\x18\x02 \x01(\x03\x12\x19\n\x11\x61\x63tion_queue_size\x18\x03 \x01(\x05\x12\x1b\n\x13policy_control_flag\x18\x04 \x01(\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "policy_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_POLICYSTEPANNOTATION"]._serialized_start = 31
    _globals["_POLICYSTEPANNOTATION"]._serialized_end = 163
# @@protoc_insertion_point(module_scope)
