# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "robot.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0brobot.proto\x12\x0crobot_teleop",\n\x0bWrenchState\x12\r\n\x05\x66orce\x18\x01 \x03(\x02\x12\x0e\n\x06torque\x18\x02 \x03(\x02"&\n\x08\x41rmState\x12\x0c\n\x04qpos\x18\x01 \x03(\x02\x12\x0c\n\x04qvel\x18\x02 \x03(\x02"\x19\n\tHandState\x12\x0c\n\x04qpos\x18\x01 \x03(\x02"\xf6\x02\n\nRobotState\x12(\n\x08left_arm\x18\x01 \x01(\x0b\x32\x16.robot_teleop.ArmState\x12)\n\tright_arm\x18\x02 \x01(\x0b\x32\x16.robot_teleop.ArmState\x12%\n\x04head\x18\x03 \x01(\x0b\x32\x17.robot_teleop.HandState\x12*\n\tleft_hand\x18\x04 \x01(\x0b\x32\x17.robot_teleop.HandState\x12+\n\nright_hand\x18\x05 \x01(\x0b\x32\x17.robot_teleop.HandState\x12&\n\x05torso\x18\x06 \x01(\x0b\x32\x17.robot_teleop.HandState\x12\x34\n\x11left_wrist_wrench\x18\x07 \x01(\x0b\x32\x19.robot_teleop.WrenchState\x12\x35\n\x12right_wrist_wrench\x18\x08 \x01(\x0b\x32\x19.robot_teleop.WrenchState"\x19\n\tArmAction\x12\x0c\n\x04qpos\x18\x01 \x03(\x02"\x1a\n\nHandAction\x12\x0c\n\x04qpos\x18\x01 \x03(\x02"3\n\rChassisAction\x12\n\n\x02vx\x18\x01 \x01(\x02\x12\n\n\x02vy\x18\x02 \x01(\x02\x12\n\n\x02wz\x18\x03 \x01(\x02"\xbe\x02\n\x0bRobotAction\x12)\n\x08left_arm\x18\x01 \x01(\x0b\x32\x17.robot_teleop.ArmAction\x12*\n\tright_arm\x18\x02 \x01(\x0b\x32\x17.robot_teleop.ArmAction\x12+\n\tleft_hand\x18\x03 \x01(\x0b\x32\x18.robot_teleop.HandAction\x12,\n\nright_hand\x18\x04 \x01(\x0b\x32\x18.robot_teleop.HandAction\x12&\n\x04head\x18\x05 \x01(\x0b\x32\x18.robot_teleop.HandAction\x12\'\n\x05torso\x18\x06 \x01(\x0b\x32\x18.robot_teleop.HandAction\x12,\n\x07\x63hassis\x18\x07 \x01(\x0b\x32\x1b.robot_teleop.ChassisActionb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "robot_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_WRENCHSTATE"]._serialized_start = 29
    _globals["_WRENCHSTATE"]._serialized_end = 73
    _globals["_ARMSTATE"]._serialized_start = 75
    _globals["_ARMSTATE"]._serialized_end = 113
    _globals["_HANDSTATE"]._serialized_start = 115
    _globals["_HANDSTATE"]._serialized_end = 140
    _globals["_ROBOTSTATE"]._serialized_start = 143
    _globals["_ROBOTSTATE"]._serialized_end = 517
    _globals["_ARMACTION"]._serialized_start = 519
    _globals["_ARMACTION"]._serialized_end = 544
    _globals["_HANDACTION"]._serialized_start = 546
    _globals["_HANDACTION"]._serialized_end = 572
    _globals["_CHASSISACTION"]._serialized_start = 574
    _globals["_CHASSISACTION"]._serialized_end = 625
    _globals["_ROBOTACTION"]._serialized_start = 628
    _globals["_ROBOTACTION"]._serialized_end = 946
# @@protoc_insertion_point(module_scope)
