# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "controller.proto"
)
# @@protoc_insertion_point(imports)
_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x63ontroller.proto\x12\x0f\x43ontrollerProto"&\n\x03Pos\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02"2\n\x04Quat\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02"I\n\x04Pose\x12\x1f\n\x01p\x18\x01 \x01(\x0b\x32\x14.ControllerProto.Pos\x12 \n\x01q\x18\x02 \x01(\x0b\x32\x15.ControllerProto.Quat"3\n\x08Skeleton\x12\'\n\tjoint_pos\x18\x01 \x03(\x0b\x32\x14.ControllerProto.Pos""\n\nThumbstick\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02"\xce\x01\n\x13\x43ontrollerTransform\x12)\n\nwrist_pose\x18\x01 \x01(\x0b\x32\x15.ControllerProto.Pose\x12\x14\n\x0chand_trigger\x18\x02 \x01(\x02\x12\x15\n\rindex_trigger\x18\x03 \x01(\x02\x12/\n\nthumbstick\x18\x04 \x01(\x0b\x32\x1b.ControllerProto.Thumbstick\x12\x14\n\x0cgrip_trigger\x18\x05 \x01(\x02\x12\x18\n\x10thumbstick_click\x18\x06 \x01(\x08"\x84\x02\n\x17\x43ontrollerTransformPair\x12\x37\n\tleft_hand\x18\x01 \x01(\x0b\x32$.ControllerProto.ControllerTransform\x12\x38\n\nright_hand\x18\x02 \x01(\x0b\x32$.ControllerProto.ControllerTransform\x12#\n\x04head\x18\x03 \x01(\x0b\x32\x15.ControllerProto.Pose\x12\'\n\x08left_arm\x18\x04 \x01(\x0b\x32\x15.ControllerProto.Pose\x12(\n\tright_arm\x18\x05 \x01(\x0b\x32\x15.ControllerProto.Pose"g\n\rHandTransform\x12)\n\nwrist_pose\x18\x01 \x01(\x0b\x32\x15.ControllerProto.Pose\x12+\n\x08skeleton\x18\x02 \x01(\x0b\x32\x19.ControllerProto.Skeleton"\xf2\x01\n\x11HandTransformPair\x12\x31\n\tleft_hand\x18\x01 \x01(\x0b\x32\x1e.ControllerProto.HandTransform\x12\x32\n\nright_hand\x18\x02 \x01(\x0b\x32\x1e.ControllerProto.HandTransform\x12#\n\x04head\x18\x03 \x01(\x0b\x32\x15.ControllerProto.Pose\x12\'\n\x08left_arm\x18\x04 \x01(\x0b\x32\x15.ControllerProto.Pose\x12(\n\tright_arm\x18\x05 \x01(\x0b\x32\x15.ControllerProto.Poseb\x06proto3'
)
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "controller_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_POS"]._serialized_start = 37
    _globals["_POS"]._serialized_end = 75
    _globals["_QUAT"]._serialized_start = 77
    _globals["_QUAT"]._serialized_end = 127
    _globals["_POSE"]._serialized_start = 129
    _globals["_POSE"]._serialized_end = 202
    _globals["_SKELETON"]._serialized_start = 204
    _globals["_SKELETON"]._serialized_end = 255
    _globals["_THUMBSTICK"]._serialized_start = 257
    _globals["_THUMBSTICK"]._serialized_end = 291
    _globals["_CONTROLLERTRANSFORM"]._serialized_start = 294
    _globals["_CONTROLLERTRANSFORM"]._serialized_end = 500
    _globals["_CONTROLLERTRANSFORMPAIR"]._serialized_start = 503
    _globals["_CONTROLLERTRANSFORMPAIR"]._serialized_end = 763
    _globals["_HANDTRANSFORM"]._serialized_start = 765
    _globals["_HANDTRANSFORM"]._serialized_end = 868
    _globals["_HANDTRANSFORMPAIR"]._serialized_start = 871
    _globals["_HANDTRANSFORMPAIR"]._serialized_end = 1113
# @@protoc_insertion_point(module_scope)
